### ISSUE TITLE
empty data_processor

### ISSUE THREAD

**Issue by taalua** [zhvng/open-musiclm#14]
Hi,

For some reason, the data processor return empty in preprocess.py:
inputs = next(self.dl_iter)

inputs is empty, however, files.append(file) in data.py are okay, all files in data/fma_large are appended correctly.

Thank you for your help.

**Comment by zhvng** [comment]
it's probably an issue with loading the data [here](https://github.com/zhvng/open-musiclm/blob/main/open_musiclm/data.py#L119-L125). The try/except is there to ignore corrupted files but it hides other errors.

When this happened to me, it was because I didn't have ffmpeg installed, which is needed to load mp3 files

**Comment by taalua** [comment]
thank you, it's ffmpeg issue.
